In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [3]:
flat = arr.flatten()

In [9]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
flat[3:6]
# Return array including index 3 till 5 excluding index 6

array([4, 5, 6])

In [11]:
flat[:5]
# As same as flat[0:5]

array([1, 2, 3, 4, 5])

In [14]:
flat[10:]
# As same as flat[10:14]

array([11, 12, 13, 14, 15])

In [18]:
print(flat[1:4])
print(flat[:3])
print(flat[::2]) # Every second element of that array

[2 3 4]
[1 2 3]
[ 1  3  5  7  9 11 13 15]


In [20]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
# Boolean Masking
mask = flat > 10
print(flat[mask])

[11 12 13 14 15]


In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [27]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[[1,2,3,4,5,6]]

array([2, 3, 4, 5, 6, 7])

In [33]:
arr.shape

(9,)

In [37]:
two_d = arr.reshape(3,3)

In [38]:
two_d.shape

(3, 3)

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr2 = np.array([1.2,1.4,2.4,6.5,3.4])

In [41]:
arr2

array([1.2, 1.4, 2.4, 6.5, 3.4])

In [42]:
arr2.dtype

dtype('float64')

In [47]:
arr2_int = arr2.astype(np.int64)

In [48]:
arr2_int.dtype

dtype('int64')

In [49]:
arr3 = np.linspace(1,100,9)

In [50]:
mask = arr3 > 50

In [51]:
print(arr3[mask])

[ 50.5    62.875  75.25   87.625 100.   ]
