In [1]:
import numpy as np

In [8]:
data = np.array([[10,20,30],
                 [15,25,35],
                 [20,30,40],
                 [25,35,45],
                 [30,40,50]])

In [10]:
mean = data.mean(axis=0)
std = data.std(axis=0)
normalised_data = (data - mean)/std
print(mean)
print(std)
print(normalised_data)

[20. 30. 40.]
[7.07106781 7.07106781 7.07106781]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
