In [1]:
import numpy as np
from numpy.ma.core import reshape

In [2]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [19]:
arr1 = np.zeros((3,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr1 = arr1 +9
print(arr1)

[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


In [22]:
arr1

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [23]:
arr2 = np.ones((3,5))

In [24]:
arr2


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr4 = np.full((3,3), 5)

In [28]:
arr4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [41]:
identity_matrix = np.eye(4, dtype = int)

In [42]:
identity_matrix.dtype

dtype('int64')

In [36]:
np.arange(1,100,12)
# 1st element 1 then add 12 to get upcoming elements until 100

array([ 1, 13, 25, 37, 49, 61, 73, 85, 97])

In [38]:
np.linspace(1, 100, 10)
#Evenly spaced between 1 and 100 with 10 spacing

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [49]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
myarr.shape


(4, 3)

In [50]:
reshaped = myarr.reshape(3,4)

In [51]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
myarr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])